baseURL = "http://example.org/"
languageCode = "de-de"
theme = "hyde"
title = "Gasthaus Cagitz"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-0b"
description = "Willkommen im Gasthaus Cagitz"
